### ISSUE TITLE
Suggestion to change `.targets` to `.props`

### ISSUE THREAD

**Issue by nvirth** [devlooped/json#52]
I suggest to rename these files from `.targets` to `.props`:  
https://github.com/devlooped/json/blob/main/src/JsonPeek/JsonPeek.targets  
https://github.com/devlooped/json/blob/main/src/JsonPoke/JsonPoke.targets  

Because that way they will be imported at the beginning of and SDK style Project, and not at the end.  
See:  
https://docs.microsoft.com/en-us/nuget/concepts/msbuild-props-and-targets#packagesconfig-projects

That's safer, the UsingTask declared by the nuget would be available in the whole Project.

**Comment by kzu** [comment]
Hi there!

The `UsingTask` is *always* evaluated *before* any targets, so the declared tasks are available always available to any targets always, regardless of whether they (the targets that use JsonPoke) exist in .props or .targets files. See the [evaluation phases](https://docs.microsoft.com/en-us/visualstudio/msbuild/build-process-overview?view=vs-2022#evaluation-phase) for reference.

That said, the reason I put it in targets, is that for `UsingTask`, the *first* to declare it "wins", unlike targets, where the *last one* to declare a target (by name) is the one that determines the implementation. Having the `JsonPoke` task declared in a .targets, therefore, allows you to override its declaration by just putting it in the .csproj or in a .props (i.e. Directory.Build.props). It makes it more flexible.

I hope that makes sense!
