### ISSUE TITLE
Adding support for peeking into Json array files

### ISSUE THREAD

**Issue by jknaudt21** [devlooped/json#70]
Currently the code does not allow us to peek in to Json array files. For example, if we try to read from a file that looks like this:
``` 
[
  {"hello" : "world"}
]
```
We get error `Error reading JObject from JsonReader. Current JsonReader item is not an object`

A simple fix is to change `JObject.Parse(...)` to `JToken.Parse(...)` in the peeking process.

**Comment by kzu** [comment]
Closed by https://github.com/devlooped/json/pull/71
